### PR TITLE
fix: Fix issues around profiles, more validation.

### LINKED ISSUE #105: Hide commands that aren't ready yet e.g `w3up insights`
Running `w3up` shows a long list of commands. 

```
Commands:
  w3up id                                    Generate a UCAN Identity
  w3up register <email>                      Register your UCAN Identity with w3up
  w3up whoami                                Show your current UCAN Identity
  w3up list                                  List your uploads
  w3up upload <path>                         Upload any file or directory to your account                                                                            [aliases: import]
  w3up upload-cars <path>                    Walk a file directory, and upload any found cars to an account
  w3up remove <cid>                          Unlink a CID from your account.                                                                                         [aliases: unlink]
  w3up import-settings <fileName>            Import a settings.json file
  w3up export-settings [filename]            Export a settings json file
  w3up reset-settings                        Delete all local settings
  w3up delegate <did>                        Delegate permissions to another DID
  w3up accounts                              List all accounts.
  w3up import-delegation <fileName> [alias]  Import a delegation.car file for access to an account (and give it an optional alias).
  w3up switch-account [alias]                Select from accounts, including imported ones.
  w3up insights <cid>                        Get insights for a CID
  w3up inspect-car <path>                    Generate an examination file from a <path> to a CAR
  w3up generate-car <filePath>               From an input file, locally generate a CAR file.
  w3up info                                  Print information about cli
  w3up open <cid>                            Open a CID in your browser on w3s.link
```

Not all of them are ready for the public yet, so let's hide the ones that aren't to make the tool a little less complicated while we are onboarding the first wave.

`w3up insights` simply reports:

```
w3up insights bafybeic6jrbud5eltx56xbw3wb2ki2wlfecskdc2grl2dyfcu7suqvnef4
✔ Getting insights for bafybeic6jrbud5eltx56xbw3wb2ki2wlfecskdc2grl2dyfcu7suqvnef4
```

so is a good candidate for hiding. Let take a moment to identity any others that are still experiemental. We should fix it so we can leave the commands in, but hide them from the global help text, so we can test things out before encouraging general use.

### LINKED ISSUE #109: `w3up accounts` doesn't validate that there is a UCAN identity locally before running
**Describe the bug**
On a fresh install, running `w3up accounts` throws this error:
image

**To Reproduce**

1. Fresh install w3up on a computer
2. Run `w3up accounts`

**Expected behavior**
A message saying there are no accounts

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #110: `w3up upload` fails with unclear error message when using an unregistered id
I reset my settings, created a new id and forgot to register before uploading... the error message didn't help me figure it out, but this seems like an easy mistake to make... can we protect the user from this by tracking if they have registered in the cli... better still, can we make a single command that does the id creation + registration flow.

```
❯ w3up reset-settings
  This will delete your settings, are you sure?
  You will lose access to anything created with your previous key/did.
  If you want to keep the previous settings, use export-settings first.

? reset: Yes
✔ Settings cleared.

~
❯ w3up id
✔ Agent DID: did:key:z6MkuwMmeY4VC7tr3Swbge5vEjgZXQ7tXuQ8VDGzVTRF8beh
✔ Account DID: did:key:z6MkihtupU1P5K4qrJxU78prQ6sQVLMiwqd6Tg4Y16P9Mpfw

~
❯ w3up upload ~/Pictures/j5
/ Uploading /Users/oli/Pictures/j5...Error: {
  "name": "HandlerExecutionError",
  "cause": {
    "name": "TypeError",
    "stack": "TypeError: Cannot read properties of null (reading 'error')\n    at null.<anonymous> (/src/ingestion/ucanto/store/provider.js:65:21)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at null.invoke3 (/node_modules/@ucanto/server/src/server.js:129:14)\n    at null.execute2 (/node_modules/@ucanto/server/src/server.js:90:18)\n    at null.handle (/node_modules/@ucanto/server/src/server.js:71:18)\n    at null.ucanHandler (/src/ingestion/ingestion.js:79:29)\n    at Runtime.handler (/node_modules/src/awslambda.ts:332:1)",
    "message": "Cannot read properties of null (reading 'error')"
  },
  "error": true,
  "stack": "HandlerExecutionError: service handler {can: \"store/add\"} error: Cannot read properties of null (reading 'error')\n    at null.invoke3 (/node_modules/@ucanto/server/src/server.js:131:19)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at null.execute2 (/node_modules/@ucanto/server/src/server.js:90:18)\n    at null.handle (/node_modules/@ucanto/server/src/server.js:71:18)\n    at null.ucanHandler (/src/ingestion/ingestion.js:79:29)\n    at Runtime.handler (/node_modules/src/awslambda.ts:332:1)",
  "message": "service handler {can: \"store/add\"} error: Cannot read properties of null (reading 'error')",
  "capability": {
    "can": "store/add",
    "with": "did:key:z6MkihtupU1P5K4qrJxU78prQ6sQVLMiwqd6Tg4Y16P9Mpfw"
  }
}
    at Client.upload (file:///usr/local/lib/node_modules/@web3-storage/w3up-cli/node_modules/@web3-storage/w3up-client/src/index.js:403:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async generateCarUploads (file:///usr/local/lib/node_modules/@web3-storage/w3up-cli/src/commands/upload.js:59:7)
    at async Object.exe [as handler] (file:///usr/local/lib/node_modules/@web3-storage/w3up-cli/src/commands/upload.js:103:3)
✖ Upload did not complete successfully, check w3up-failure.log
```

### LINKED ISSUE #112: Fix regressions around profiles
id --reset no longer works.
clean up some things around checking id / etc, as this no longer makes sense with root settings.

### PR DESCRIPTION
**Pull request by ice-breaker-tg**
closes #112
closes #110
closes #109
closes #105

### CODE REVIEW

File: src/validation.js [hunk 1]
```diff
@@ -23,15 +23,11 @@ export const isEmail = (email) => {
...
-      throw 'A CID was not provided'
-    }
-    parseLink(cid)
-    return true
-  } catch (err) {
-    throw err
+  if (!cid) {
+    throw 'A CID was not provided'
   }
+  parseLink(cid)
```
Comment (dashcraft) [inline src/validation.js:29]: Is it ever possible for this to fail?

**Review by dashcraft — APPROVED** [review]
Approved with 1 minor comment, wanted to make sure an error case for parsing a cid is handled just in case?
